### ISSUE TITLE
No share button fix?

### ISSUE THREAD

**Issue by GJ-sanjay** [Ankan-cyber/resumeio2pdfnextjs#2]
Theyve removed the share button and the share option read mode is no more any fixes?

**Comment by Ankan-cyber** [comment]
I dont think so.

**Comment by ngntriminh** [comment]
> Theyve removed the share button and the share option read mode is no more any fixes?

I have developed a Chrome extension for that, now the process is really simple. Check my repo here: https://github.com/ngntriminh/ResumeGrabber.

**Comment by GJ-sanjay** [comment]
is it working?

**Comment by Ankan-cyber** [comment]
yeah will check it out

**Comment by ngntriminh** [comment]
> yeah will check it out

Thank you for trying it. Did it work as expected? I see that you've just closed the issue.

**Comment by Ankan-cyber** [comment]
yeah nicely done it works perfectly, I will add this link to my website and repo

**Comment by ngntriminh** [comment]
> yeah nicely done it works perfectly, I will add this link to my website and repo

Thank you for your feedback, I appreciate that!

**Comment by Ankan-cyber** [comment]
I just have one suggestion. The extension works great, but for non technical people its a hassle, downloading then go into developer mode and installing, I made this project in the first place because of making the process simpler, if you can get this extension to publish on chrome web store that would be awesome. (btw I seen your walkthrough on youtube  it makes it little easier)

**Comment by ngntriminh** [comment]
> I just have one suggestion. The extension works great, but for non technical people its a hassle, downloading then go into developer mode and installing, I made this project in the first place because of making the process simpler, if you can get this extension to publish on chrome web store that would be awesome. (btw I seen your walkthrough on youtube it makes it little easier)

Yeah, actually used to plan to make it live on the Chrome Web Store but I don't have the developer account and I'm afraid it may go against some rules. Actually to make it simpler, just host a web app as what you did but the web app may be slow or not accessible if a lot of people access it whereas the extension is not. By the way thanks for your suggestion, the reason why I made the tutorial video is to guide people how to install it and I believe it's not that hard. I may try to publish it in the Chrome Web Store in the future.

**Comment by Ankan-cyber** [comment]
Yeah nice, Great work

**Comment by Ankan-cyber** [comment]
@ngntriminh added your repo to the website check it out

**Comment by ngntriminh** [comment]
> @ngntriminh added your repo to the website check it out

@Ankan-cyber Thank you so much my friend 🙏. That's really kind of you!
