### ISSUE TITLE
Hey, I stopped the project (extension), so please update your site if needed

### ISSUE THREAD

**Issue by ngntriminh** [Ankan-cyber/resumeio2pdfnextjs#3]
UPDATE: Sorry guys. I stopped the project (ResumeGrabber) because:

- An Indian thief has stolen my code to claim the false ownership and profit as well as monetizing from it.
- GitHub has taken down my project, I don't know why, maybe it violates their service. Or maybe the thief has reported it because he wanted to eradicate my original project.
- I won't share it elsewhere because the thief will still steal it and because GitHub is the best place to update my software. It's frustrating, but thank you for supporting me!

**Comment by Ankan-cyber** [comment]
ok. what happened please elaborate
